format_version = 1
generator_hash = "01c5a3cf088a5f8719983b358413b9e503a6a4d242019ff791cbd22a2152b27b"
literate_hash = "53979078af92c06d7ad0bcd95f320b6bbe9a942f96ad809d35eb28eac436bca5"
src_hash = "343afa0eba773f8e9793e8b0128b9ec553718ed31ba8d1c50f6eba92141ba78f"
