format_version = 1
generator_hash = "01c5a3cf088a5f8719983b358413b9e503a6a4d242019ff791cbd22a2152b27b"
literate_hash = "9db41f04faf3b2d2ea1753ecd9ab9a58bbceacf68d642f70cf85f9fe0d00955e"
src_hash = "d733f60fbe4ac93805b05541746069f3cdbe2948ce3c4526d23b61c9a7cd20f9"
