format_version = 1
generator_hash = "01c5a3cf088a5f8719983b358413b9e503a6a4d242019ff791cbd22a2152b27b"
literate_hash = "53979078af92c06d7ad0bcd95f320b6bbe9a942f96ad809d35eb28eac436bca5"
src_hash = "d21c1ab6f4928d511d2a87f2271ad462b88a162e5cca01c6af6d4c914266eb15"
