format_version = 1
generator_hash = "01c5a3cf088a5f8719983b358413b9e503a6a4d242019ff791cbd22a2152b27b"
literate_hash = "9db41f04faf3b2d2ea1753ecd9ab9a58bbceacf68d642f70cf85f9fe0d00955e"
src_hash = "c26500f37c23b5fb821ed3785acfcd94b027d19fe1ad9d05aa69a000b7da813b"
