format_version = 1
generator_hash = "01c5a3cf088a5f8719983b358413b9e503a6a4d242019ff791cbd22a2152b27b"
literate_hash = "35bedbc6b175b6e62fe0aca4d6b7355b337713e9de9243ba4cfb4875f4ca6aef"
src_hash = "da08193639cc4afabaed9392b8a3e3f260fe7e8903ddffd8689943942e1907e1"
