format_version = 1
generator_hash = "01c5a3cf088a5f8719983b358413b9e503a6a4d242019ff791cbd22a2152b27b"
literate_hash = "bcd13a29d9e9dfe62287735778626d7e1151421f85907aadc2888c0a8f8ca939"
src_hash = "8dcc2f1482eac6dc74160a442b8c6bebdc907e80257f13cc05571f1a5e811651"
